"""Lista completa dos controlos do QNRCS v2 (Anexo I do Aviso 5146/2026/2).

Gerado automaticamente por extrair_controlos_qnrcs.py.
Não editar manualmente — para regenerar, correr o script novamente.
"""

CONTROLOS_COMPLETOS = {
    "GR": [  # Gerir — 31 controlos
        ("GR.CA-1", "As políticas e processos de gestão dos riscos da cadeia de abastecimento são identificados, estabelecidos, avaliados e geridos"),
        ("GR.CA-2", "Os papéis e responsabilidades dos parceiros, fornecedores e clientes no âmbito da"),
        ("GR.CA-3", "Os processos de gestão dos riscos de cibersegurança da cadeia de abastecimento"),
        ("GR.CA-4", "Os fornecedores são periodicamente avaliados"),
        ("GR.CA-5", "As entidades definem e integram nos contratos e outros acordos com fornecedores"),
        ("GR.CA-6", "Antes da contratação de fornecedores ou terceiros são realizadas as devidas diligências para reduzir os riscos"),
        ("GR.CA-7", "A entidade avalia os riscos de cibersegurança da cadeia de abastecimento"),
        ("GR.CA-8", "O Plano de Resposta a Incidentes e o Plano de Recuperação de Desastres são testados"),
        ("GR.CA-9", "As práticas de cibersegurança da cadeia de abastecimento são integradas em programas de cibersegurança e de gestão de riscos organizacionais, e o seu desempenho é monitorizado"),
        ("GR.CA-10", "Aquando da definição de processos de gestão dos riscos da cadeia de abastecimento"),
        ("GR.CO-1", "A missão, visão, estratégia de gestão dos riscos e objetivos da entidade são definidos"),
        ("GR.CO-2", "As necessidades e expectativas das partes interessadas internas e externas são compreendidas e encontram-se refletidas na gestão dos riscos de cibersegurança da entidade"),
        ("GR.CO-3", "Os requisitos legais, regulamentares e contratuais para a cibersegurança, são compreendidos e geridos"),
        ("GR.CO-4", "Os ativos e serviços críticos da entidade dos quais as partes interessadas externas"),
        ("GR.CO-5", "Os requisitos de resiliência necessários para suportar a prestação de serviços críticos"),
        ("GR.CO-6", "Os ativos e serviços externos dos quais a entidade depende, são identificados e comunicados"),
        ("GR.FR-1", "Os órgãos de gestão, direção e administração compreendem as suas funções, responsabilidades e promovem uma cultura de cibersegurança, ética e de melhoria contínua"),
        ("GR.FR-2", "São atribuídos recursos adequados e proporcionais à estratégia de gestão do risco de"),
        ("GR.FR-3", "As funções, responsabilidades e autoridades em matéria de cibersegurança são definidas e comunicadas ao pessoal, fornecedores e partes interessadas"),
        ("GR.FR-4", "A cibersegurança é contemplada nos processos de gestão de recursos humanos"),
        ("GR.GR-1", "O apetite e a tolerância ao risco da entidade são definidos, aprovados, comunicados"),
        ("GR.GR-2", "Os processos de gestão dos riscos de cibersegurança estão incluídos na estratégia"),
        ("GR.GR-3", "A entidade define a sua estratégia de tratamento do risco"),
        ("GR.GR-4", "A entidade estabelece um canal de comunicação interno para partilha de riscos de"),
        ("GR.GR-5", "A entidade define uma Política de Gestão dos Riscos de Cibersegurança a qual prevê"),
        ("GR.PP-1", "As Políticas para a gestão de Cibersegurança, incluindo a Política de Cibersegurança, são definidas, aprovadas e mantidas"),
        ("GR.PP-2", "O Plano de Resposta a Incidentes é definido, comunicado, mantido e melhorado"),
        ("GR.PP-3", "O Plano de Recuperação de Desastres é definido, comunicado, mantido e melhorado"),
        ("GR.SP-1", "Os resultados da estratégia de gestão dos riscos de cibersegurança são analisados"),
        ("GR.SP-2", "A estratégia de gestão dos riscos de cibersegurança é revista regularmente e adaptada"),
        ("GR.SP-3", "O desempenho da gestão dos riscos de cibersegurança da entidade é avaliado e revisto"),
    ],
    "ID": [  # Identificar — 19 controlos
        ("ID.AR-1", "As vulnerabilidades dos ativos são identificadas e documentadas com base na metodologia definida"),
        ("ID.AR-2", "A entidade partilha informações sobre ameaças de cibersegurança com partes interessadas"),
        ("ID.AR-3", "As ameaças internas e externas são identificadas e documentadas com base na metodologia definida"),
        ("ID.AR-4", "São identificados e registados potenciais impactos e as respetivas probabilidades de"),
        ("ID.AR-5", "A entidade avalia os riscos identificados"),
        ("ID.AR-6", "A entidade garante que as respostas aos riscos são identificadas e priorizadas"),
        ("ID.AR-7", "A entidade define processos para receber informação, analisar e responder a vulnerabilidades provenientes de fontes internas e externas"),
        ("ID.GA-1", "Os equipamentos e os demais recursos físicos existentes na entidade são inventariados"),
        ("ID.GA-2", "Os recursos lógicos que suportam os processos dos serviços da entidade são inventariados"),
        ("ID.GA-3", "As redes e fluxos de comunicação são mapeados"),
        ("ID.GA-4", "As redes e sistemas de informação externos são identificados e catalogados"),
        ("ID.GA-5", "Os ativos são classificados de acordo com a sua criticidade"),
        ("ID.GA-6", "Os inventários de dados e metadados correspondentes para tipos de dados designados"),
        ("ID.GA-7", "Sistemas, hardware, software, serviços e dados são geridos ao longo dos seus ciclos"),
        ("ID.GA-8", "Os dados são destruídos de acordo com a Política de Classificação e Gestão de Dados"),
        ("ID.GA-9", "A entidade implementa um processo de gestão de alterações"),
        ("ID.MC-1", "As melhorias são identificadas através de avaliações e a informação é partilhada com"),
        ("ID.MC-2", "São identificadas melhorias a partir de testes e exercícios de cibersegurança"),
        ("ID.MC-3", "As melhorias são identificadas a partir da execução de processos, procedimentos"),
    ],
    "PR": [  # Proteger — 23 controlos
        ("PR.FC-1", "Todo o pessoal é sensibilizado e formado em matérias de cibersegurança"),
        ("PR.FC-2", "O pessoal com funções especializadas em cibersegurança recebe formação adequada"),
        ("PR.GA-1", "Os ciclos de vida de gestão de identidades são definidos"),
        ("PR.GA-2", "A entidade verifica a identidade dos utilizadores e vincula-a às respetivas credenciais"),
        ("PR.GA-3", "São definidos mecanismos de autenticação de utilizadores, dispositivos e outros ativos"),
        ("PR.GA-4", "As afirmações de identidade são protegidas, transmitidas e verificadas"),
        ("PR.GA-5", "As permissões de acesso, os direitos e as autorizações são definidas numa política,"),
        ("PR.GA-6", "Os controlos de acesso físico a ativos da entidade são geridos, monitorizados e aplicados em função do risco"),
        ("PR.GA-7", "A entidade gere os seus acessos remotos"),
        ("PR.RI-1", "A entidade protege a integridade das redes de comunicações"),
        ("PR.RI-2", "Os ambientes de desenvolvimento e de teste são separados de ambientes de produção"),
        ("PR.RI-3", "Os ativos tecnológicos da entidade são protegidos de ameaças naturais"),
        ("PR.RI-4", "São implementados mecanismos para cumprir os requisitos de resiliência em situações"),
        ("PR.RI-5", "A entidade planeia a capacidade adequada dos recursos para garantir a disponibilidade"),
        ("PR.SD-1", "A entidade protege a confidencialidade, integridade e disponibilidade dos dados em"),
        ("PR.SD-2", "A entidade protege a confidencialidade, integridade e disponibilidade dos dados em"),
        ("PR.SD-3", "A entidade implementa proteções que evitem exfiltração de dados"),
        ("PR.SD-4", "A entidade protege a confidencialidade e integridade dos dados em uso nos sistemas críticos"),
        ("PR.SD-5", "São realizadas, mantidas e testadas cópias de segurança dos dados da entidade"),
        ("PR.SP-1", "É criada e mantida uma configuração base de redes e sistemas de informação que"),
        ("PR.SP-2", "Os logs de sistemas e o histórico de atividades são documentados, implementados"),
        ("PR.SP-3", "A instalação e execução de software não autorizado são impedidas"),
        ("PR.SP-4", "É implementado um ciclo de vida de desenvolvimento seguro de software"),
    ],
    "DE": [  # Detectar — 13 controlos
        ("DE.AE-1", "Os eventos detetados são analisados"),
        ("DE.AE-2", "Os eventos são recolhidos e correlacionados a partir de várias fontes e sensores"),
        ("DE.AE-3", "O impacto estimado e o âmbito dos eventos adversos detetados são compreendidos"),
        ("DE.AE-4", "As informações sobre deteções de eventos são comunicadas"),
        ("DE.AE-5", "As informações sobre ciberameaças e outras informações contextuais são integradas"),
        ("DE.AE-6", "Os critérios para a declaração de incidentes são definidos"),
        ("DE.MC-1", "As redes e sistemas de informação são monitorizados para detetar potenciais incidentes"),
        ("DE.MC-2", "O ambiente físico é monitorizado para possibilitar a deteção de potenciais incidentes"),
        ("DE.MC-3", "A atividade dos colaboradores é monitorizada para se detetar potenciais incidentes"),
        ("DE.MC-4", "A entidade identifica e implementa mecanismos para deteção de código malicioso"),
        ("DE.MC-5", "A utilização de aplicações não autorizadas em dispositivos móveis é detetada"),
        ("DE.MC-6", "As atividades dos prestadores de serviços externos são monitorizadas para deteção"),
        ("DE.MC-7", "O hardware, software, os ambientes em produção e os seus dados são monitorizados"),
    ],
    "RS": [  # Responder — 13 controlos
        ("RS.AI-1", "É realizada uma análise forense para determinar o que ocorreu durante um incidente"),
        ("RS.AI-2", "As ações realizadas durante uma investigação são registadas e a integridade e proveniência dos registos são preservadas"),
        ("RS.AI-3", "Os dados e metadados do incidente são recolhidos, e a sua integridade e proveniência"),
        ("RS.AI-4", "O impacto do incidente é estimado e validado"),
        ("RS.GI-1", "O Plano de Resposta a Incidentes é executado, em coordenação com as partes interessadas, durante ou após a ocorrência de um incidente"),
        ("RS.GI-2", "As notificações dos sistemas de deteção são triadas e validadas"),
        ("RS.GI-3", "Os incidentes são categorizados de acordo com o Plano de Resposta a Incidentes"),
        ("RS.GI-4", "Os incidentes são escalados ou elevados conforme necessário"),
        ("RS.GI-5", "São aplicados os critérios para iniciar a recuperação de incidentes"),
        ("RS.MI-1", "Os incidentes são contidos"),
        ("RS.MI-2", "Os incidentes são resolvidos"),
        ("RS.NC-1", "As partes interessadas internas e externas são notificadas dos incidentes"),
        ("RS.NC-2", "Existe partilha voluntária de informação com partes interessadas externas"),
    ],
    "RC": [  # Recuperar — 8 controlos
        ("RC.CO-1", "As atividades de recuperação são comunicadas às partes interessadas, bem como"),
        ("RC.CO-2", "As atualizações sobre a recuperação de incidentes são partilhadas utilizando métodos"),
        ("RC.PR-1", "A entidade segue um plano de recuperação durante ou após um incidente"),
        ("RC.PR-2", "As ações de recuperação são definidas, priorizadas e executadas"),
        ("RC.PR-3", "A integridade das cópias de segurança e de outros ativos de restauro é verificada"),
        ("RC.PR-4", "A entidade considera os seus serviços críticos e a gestão dos riscos de cibersegurança"),
        ("RC.PR-5", "A integridade dos ativos restaurados é verificada, os sistemas e serviços são restaurados e o estado de normal funcionamento é confirmado"),
        ("RC.PR-6", "O fim da recuperação do incidente é documentado e declarado com base em critérios"),
    ],
}

# Total: 107 controlos